---
- name: Cria novo projeto
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Listar projetos no OpenShift
      kubernetes.core.k8s:
            name: testing
            api_version: v1
            kind: Namespace
            state: present
      register: projects