---
- name: Convert CentOS 8 to RHEL 8
  hosts: all
  become: true

  vars:
    activation_key: "automates"
    organization_id: "14022285"

  tasks:
    - name: Ensure the system is updated to latest packages
      yum:
        name: '*'
        state: latest

    - name: Ensure the repository for convert2rhel is present
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/convert2rhel.repo
        content: |
          [convert2rhel]
          name=Convert to RHEL Repository
          baseurl=https://cdn-public.redhat.com/content/public/addon/dist/convert2rhel8/8/x86_64/os/
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        mode: '0644'
        owner: root
        group: root

    - name: Install convert2rhel
      ansible.builtin.yum:
        name: convert2rhel
        state: present

    - name: Run convert2rhel to convert CentOS to RHEL
      ansible.builtin.command:
        cmd: convert2rhel --no-rpm-va --disable-submgr --enablerepo convert2rhel --yes
      register: conversion_result

    - name: Output the results of the conversion
      ansible.builtin.debug:
        msg: "{{ conversion_result.stdout }}"

    - name: Register system with subscription-manager
      redhat_subscription:
        state: present
        activationkey: "{{ activatio_key }}"
        org_id: "{{ organization_id }}"
        pool: '^Red Hat Enterprise Server$'
        auto_attach: true

