---
- name: Inicia a migração do vmware
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Criar plano de migração do VMWARE
      kubernetes.core.k8s:
        state: present
        src: ../files/plan.yaml