---
- name: Inicia a migração do vmware
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Iniciar o plano de migração
      kubernetes.core.k8s:
        state: present
        src: ../files/start_migration.yaml