---
- name: Inicie Live Migration of a VM in OpenShift Virtualization
  hosts: localhost  
  gather_facts: false

  vars:
    api_version: kubevirt.io/v1
    vm_name: "example-vm"
    namespace: "default" 

  tasks:
    - name: Inicia VM live migration
      kubernetes.core.k8s:
        state: present
        api_version: "{{ api_version }}"
        kind: VirtualMachineInstanceMigration
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}-migration"
        definition:
          spec:
            vmiName: "{{ vm_name }}"
      register: migration_result

    - name: Verifica status de migracao
      kubernetes.core.k8s_info:
        api_version: "{{ api_version }}"
        kind: VirtualMachineInstanceMigration
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}-migration"
      register: migration_status
      until: migration_status.resources[0].status.phase == "Succeeded"
      retries: 30
      delay: 10

    - name: Output migration result
      ansible.builtin.debug:
        msg: "Migration of VM '{{ vm_name }}' has completed successfully."