---
- name: Demo Automation
  hosts: localhost
  gather_facts: false

  vars:
    openshift_namespace: "openshift-mtv"
  tasks:

    - name: Fetch Migration Plan Statuses from OpenShift
      k8s_info:
        api_version: forklift.konveyor.io/v1beta1  # Adjust the api_version based on your installation
        kind: Plan  # This might be 'Plan' instead of 'MigrationPlan', depending on your MTV version
        namespace: "{{ openshift_namespace }}"
      register: migration_plans

    - name: Display Migration Plan Statuses
      debug:
        var: migration_plans.resources