---
- name: Demo Automation
  hosts: localhost
  gather_facts: false

  vars:
    openshift_namespace: "openshift-mtv"
  tasks:

    - name: Login to OpenShift
      command: oc login --token={{ lookup('env', 'OC_TOKEN') }} --server={{ lookup('env', 'OC_SERVER') }}
      changed_when: false
      when: lookup('env', 'OC_TOKEN') is defined and lookup('env', 'OC_SERVER') is defined

    - name: Listar todos os planos de migração
      command: oc get migrationplan -n {{ openshift_namespace }} -o json
      register: migration_plans

    - name: Realizando Parser do status de migração
      set_fact:
        migration_status: "{{ (migration_plans.stdout | from_json).items | map(attribute='status') | list }}"

    - name: Informando o Status de migração
      debug:
        msg: "Migration Plan Statuses: {{ migration_status }}"