---
- name: Demo Automation
  hosts: localhost
  gather_facts: false

  vars:
    openshift_namespace: "openshift-mtv"
  tasks:

    - name: Fetch Migration Plan Statuses from OpenShift
      k8s_info:
        api_version: migration.openshift.io/v1alpha1
        kind: MigrationPlan
        namespace: "{{ openshift_namespace }}"
        verify_ssl: no  # Set to yes in production if your cluster uses signed certificates
      register: migration_plans

    - name: Display Migration Plan Statuses
      debug:
        msg: "{{ item.status }}"
      loop: "{{ migration_plans.resources }}"